jobs:
  test:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Pull Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./main/main

name: Action

on:
  schedule:
    - cron: "40 1/3 * * *"
